default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= (ENV['STAKEOUT_SERVER_THREADS'].to_i + 2) || 10 %>

development:
  <<: *default
  url:  <%= ENV["STAKEOUT_DATABASE_URL"] %>

test:
  <<: *default
  url:  <%= ENV["STAKEOUT_DATABASE_URL_TEST"] %>

production:
  <<: *default
  url:  <%= ENV["STAKEOUT_DATABASE_URL"] %>

# benchmark:
#   <<: *default
#   url:  <%= ENV["STAKEOUT_DATABASE_URL"] %>
